apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: updates-lab 
spec:
  replicas: 10
  selector:
    matchLabels:
      app: frontend-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-container
        image: kodekloud/webapp-color:v1
        ports:
        - containerPort: 8080
